### PR TITLE
fix: use core.info for logging, remove unused fs import

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
See https://github.com/actions/javascript-action/issues/27
Need to use https://github.com/actions/toolkit/tree/main/packages/core#logging
for logging.

Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

### CODE REVIEW

**Comment by HarikrishnanBalagopal** [comment]
I have not changed `dist/index.js` to keep the diff to a minimum.

**Comment by eregon** [comment]
As far as I know `console.log()` works fine.
Do you have an example where it's not printed?

What is meant in the docs is `core.debug("...")` is only shown if enabled, but that's something else.

**Comment by eregon** [comment]
I.e. it worked fine in https://github.com/eregon/publish-release/runs/1392149962?check_suite_focus=true#step:3:6

**Comment by HarikrishnanBalagopal** [comment]
> What is meant in the docs is `core.debug("...")` is only shown if enabled, but that's something else.

https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging
To see `core.debug` messages you need to set the secret `ACTIONS_STEP_DEBUG` to `true`.
Can also set the secret `ACTIONS_RUNNER_DEBUG` to true for debug messages from the Github runner itself.

**Comment by HarikrishnanBalagopal** [comment]
> As far as I know `console.log()` works fine.
> Do you have an example where it's not printed?

I was having problems earlier where it wasn't printed but I tested `console.log` just now and it seems to work.

**Review by eregon — APPROVED** [review]
Thanks for the cleanup

**Pull request merged**
